framework:
    rate_limiter:
        scheb_two_factor:
            policy: 'fixed_window'
            limit: 5
            interval: '10 minutes'
        scheb_two_factor_resend:
            policy: 'fixed_window'
            limit: 3
            interval: '10 minutes'