# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        enabled: true                  # If email authentication should be enabled, default false
        digits: 4                      # Number of digits in authentication code
        template: app/frontend/security/login_2fa.html.twig   # Template used to render the authentication form
        mailer: App\Security\TwoFactorCodeMailer